extends Node

var rng = RandomNumberGenerator.new()

var proj
var aqi
var cost
var output

func rand(good : bool):
	if (good == true):
		return randomize_good()
	else:
		return randomize_bad()
		
func randomize_project(good : bool):
	if (good == true):
		return eco_friendly_projects.pick_random()
	else:
		return ominous_projects.pick_random()
	
func randomize_bad():
	proj = randomize_project(false)
	aqi = rng.randf_range(1.0, 6.0)
	cost = rng.randf_range(0.0, 30.0)
	output = rng.randf_range(30, 100)
	set_values()
	return [aqi,cost,output]
	
func randomize_good():
	var version = rng.randf_range(0, 10)
	if (version >= 8):
		return randomize_aqi_reducer()
	else:
		proj = randomize_project(true)
		aqi = 0
		cost = rng.randf_range(-15.0, 5.0)
		output = rng.randf_range(40, 80)
		set_values()
		return [aqi,cost,output]

func randomize_aqi_reducer():
	proj = randomize_project(true)
	aqi = rng.randf_range(-8, -4)
	cost = rng.randf_range(-20.0, -10.0)
	output = 0
	set_values()
	return [aqi,cost,output]

func set_values():
	var proj_no_nl = proj.replace("\n", " ")
	aqi = snapped(aqi, 0.01)
	cost = snapped(cost, 0.01)
	output = snapped(output, 0.01)
	
	$Title.set_child_text(proj)
	$Sentence.set_text(project_cost[proj_no_nl] % cost)
	
	var dupePage = load("res://Scenes/Pages/Presets/Basic4Dummy.tscn")
	var dupePageInst = dupePage.instantiate()
	get_parent().add_sibling(dupePageInst)
	dupePageInst.position = get_parent().position + Vector2(50,50)
	
	dupePageInst.get_child(3).get_child(0).set_child_text(proj)
	dupePageInst.get_child(3).get_child(1).set_text(aqi_text[proj_no_nl] % aqi)
	
	var dupePage2 = load("res://Scenes/Pages/Presets/Basic4Dummy.tscn")
	var dupePageInst2 = dupePage2.instantiate()
	get_parent().add_sibling(dupePageInst2)
	dupePageInst2.position = get_parent().position + Vector2(100,100)
	
	dupePageInst2.get_child(3).get_child(0).set_child_text(proj)
	dupePageInst2.get_child(3).get_child(1).set_text(energy_output[proj_no_nl] % output)









var ominous_projects = [
	"Strategic Defoliation\nInitiative",
	"Deep Bore\nNuclear Waste Storage",
	"Experimental Seismic\nTesting (Fracking)",
	"Remote Arctic\nResource Exploitation",
	"Unregulated Deep-Sea\nMining",
	"Forced Relocation\nfor Dam Construction",
	"Large-Scale Incineration\nProject",
	"Controversial Pesticide\nDeployment",
	"Offshore Oil\nPlatform Expansion",
	"Unmonitored Chemical\nWaste Discharge",
	"Tax Haven\nResource Transfer",
	"Lobby-Driven Regulatory\nExemption",
	"Subsidized Fossil\nFuel Infrastructure",
	"Offshore Data\nStorage (for tax evasion)",
	"Non-Disclosure Agreement\nLand Acquisition",
	"Strategic Price\nFixing Initiative",
	"Environmental Impact\nReport Suppression",
	"Delayed Infrastructure\nMaintenance",
	"Political Campaign\nFunding (lobbying)",
	"Contract Bid\nRigging",
]

var eco_friendly_projects = [
	"Community Solar\nMicrogrid Implementation",
	"Urban Green\nRoof Expansion",
	"Coastal Wetland\nRestoration Project",
	"Reforestation and\nNative Species Planting",
	"Public Transportation\nElectrification",
	"Sustainable Agriculture\nand Food Distribution",
	"Wildlife Corridor\nDevelopment",
	"Water Conservation\nand Purification Initiative",
	"Renewable Energy\nStorage Deployment",
	"Habitat Restoration\nand Invasive Species",
	"Solar Farm\nConstruction",
	"Wind Turbine\nInstallation",
	"Hydroelectric Dam\nUpgrade",
	"Geothermal Energy\nPlant Development",
	"Biomass Energy\nFacility Construction",
	"Renewable Energy\nGrid Interconnection",
	"Energy Efficiency\nImprovement Program",
	"Sustainable Building\nConstruction",
	"Electric Vehicle\nCharging Infrastructure",
	"Smart Grid\nTechnology Deployment",
]

var aqi_text = {
	# good
	"Community Solar Microgrid Implementation": "Community solar microgrid projects help reduce reliance on fossil fuels, significantly decreasing harmful air pollutants. This could result in an AQI improvement of %s, with a reduction of 60 tons of CO₂ emissions and 20 tons of particulate matter. The long-term benefits include improved public health due to cleaner air and reduced respiratory issues in surrounding communities.",
	"Urban Green Roof Expansion": "Expanding urban green roofs helps absorb carbon dioxide and other pollutants, improving urban air quality. The AQI could improve by AQI impact of %s, with a reduction of 15 tons of CO₂ and 5 tons of particulate matter. This project could also contribute to reducing the urban heat island effect, enhancing the overall livability of cities.",
	"Coastal Wetland Restoration Project": "Restoring coastal wetlands improves air quality by filtering pollutants and enhancing carbon sequestration. The AQI could improve by AQI impact of %s, reducing CO₂ by 35 tons and particulate matter by 10 tons. Wetland restoration projects also protect biodiversity and offer natural flood control, which benefits communities living near the coast.",
	"Reforestation and Native Species Planting": "Reforestation and planting native species help absorb CO₂ and purify the air. The AQI could improve by AQI impact of %s, with a reduction of 80 tons of CO₂ and 30 tons of particulate matter. In addition to improving air quality, these projects help combat climate change and restore critical ecosystems.",
	"Public Transportation Electrification": "Electrifying public transportation reduces air pollution from fossil fuel-based vehicles, leading to better air quality. The AQI could improve by AQI impact of %s, with a reduction of 50 tons of CO₂ and 25 tons of particulate matter. Electrification projects also reduce urban traffic congestion, providing additional benefits to public health and mobility.",
	"Sustainable Agriculture and Food Distribution": "Sustainable agricultural practices minimize air pollution by reducing the need for chemical fertilizers and pesticides. The AQI could improve by AQI impact of %s, decreasing CO₂ emissions by 40 tons and particulate matter by 15 tons. The project promotes local food distribution, reducing transportation-related pollution and improving community health.",
	"Wildlife Corridor Development": "Wildlife corridors support biodiversity and can improve air quality by enhancing local ecosystems' natural air filtration. The AQI could improve by AQI impact of %s, with reductions in CO₂ emissions by 20 tons and particulate matter by 10 tons. These projects also help mitigate habitat fragmentation and enhance biodiversity, which benefits both human and wildlife populations.",
	"Water Conservation and Purification Initiative": "Water conservation and purification projects reduce the need for energy-intensive water treatment processes, lowering emissions that contribute to poor air quality. The AQI could improve by AQI impact of %s, reducing CO₂ by 25 tons and particulate matter by 5 tons. Additionally, these initiatives promote sustainability and help preserve water resources for future generations.",
	"Renewable Energy Storage Deployment": "Deploying renewable energy storage solutions supports the use of clean energy and reduces reliance on polluting fossil fuels. The AQI could improve by AQI impact of %s, decreasing CO₂ emissions by 75 tons and particulate matter by 20 tons. Energy storage projects help stabilize renewable energy grids and increase the efficiency of renewable resources.",
	"Habitat Restoration and Invasive Species": "Restoring habitats and removing invasive species supports biodiversity and enhances natural air filtration systems, improving overall air quality. The AQI could improve by AQI impact of %s, with a reduction of 60 tons of CO₂ and 18 tons of particulate matter. These projects also help prevent further environmental degradation and promote ecological resilience.",
	"Solar Farm Construction": "Building solar farms provides clean energy and reduces the need for polluting fossil fuels, leading to significant air quality improvements. The AQI could improve by AQI impact of %s, with a reduction of 150 tons of CO₂ and 30 tons of particulate matter. Solar farms contribute to long-term energy sustainability and help mitigate climate change.",
	"Wind Turbine Installation": "Wind turbine projects generate clean, renewable energy without emitting harmful pollutants, helping to improve air quality. The AQI could improve by AQI impact of %s, reducing CO₂ emissions by 90 tons and particulate matter by 25 tons. Wind energy also offers long-term economic benefits by providing jobs and reducing dependence on fossil fuels.",
	"Hydroelectric Dam Upgrade": "Upgrading hydroelectric dams enhances energy production without releasing pollutants, improving air quality in the surrounding area. The AQI could improve by AQI impact of %s, with a reduction of 65 tons of CO₂ and 20 tons of particulate matter. These upgrades contribute to a more sustainable energy infrastructure and reduce reliance on fossil fuels.",
	"Geothermal Energy Plant Development": "Geothermal energy plants harness clean, renewable energy from the Earth's heat, reducing the need for carbon-emitting energy sources. The AQI could improve by AQI impact of %s, with a reduction of 50 tons of CO₂ and 15 tons of particulate matter. Geothermal energy provides a stable, sustainable energy source with minimal environmental impact.",
	"Biomass Energy Facility Construction": "Biomass energy facilities produce clean energy from organic waste, reducing reliance on fossil fuels and lowering air pollution. The AQI could improve by AQI impact of %s, reducing CO₂ emissions by 40 tons and particulate matter by 12 tons. Biomass energy supports the circular economy by converting waste into valuable energy.",
	"Renewable Energy Grid Interconnection": "Connecting renewable energy grids helps integrate clean energy sources, reducing the use of fossil fuels and lowering air pollution. The AQI could improve by AQI impact of %s, with a reduction of 85 tons of CO₂ and 28 tons of particulate matter. Grid interconnection projects provide more reliable and sustainable energy, reducing the overall environmental footprint.",
	"Energy Efficiency Improvement Program": "Energy efficiency programs reduce energy consumption, decreasing the emissions associated with power generation and improving air quality. The AQI could improve by AQI impact of %s, reducing CO₂ by 55 tons and particulate matter by 18 tons. These programs also help lower energy costs and promote sustainability in buildings and industries.",
	"Sustainable Building Construction": "Constructing sustainable buildings with energy-efficient designs reduces the carbon footprint and lowers the emissions that contribute to poor air quality. The AQI could improve by AQI impact of %s, with a reduction of 30 tons of CO₂ and 10 tons of particulate matter. These buildings also provide healthier indoor environments, improving the quality of life for their occupants.",
	"Electric Vehicle Charging Infrastructure": "Expanding electric vehicle charging infrastructure supports the transition to cleaner transportation, reducing emissions from fossil fuel-powered vehicles. The AQI could improve by AQI impact of %s, reducing CO₂ emissions by 80 tons and particulate matter by 22 tons. This infrastructure enhances the accessibility of electric vehicles, further decreasing urban air pollution.",
	"Smart Grid Technology Deployment": "Deploying smart grid technologies optimizes energy use, reducing waste and lowering emissions associated with energy generation. The AQI could improve by AQI impact of %s, with a reduction of 120 tons of CO₂ and 35 tons of particulate matter. Smart grids provide more efficient energy distribution and support the integration of renewable energy sources into the grid.",
	# bad
	"Strategic Defoliation Initiative": "Strategic defoliation projects can degrade air quality by releasing carbon dioxide, particulate matter, and other pollutants. These emissions may result in an AQI increase of %s, leading to a rise in the PM2.5 levels by 15 micrograms/m³ of fine particles in the air. This environmental degradation can have a lasting impact on public health, resulting in harmful effects on respiratory health for vulnerable populations.",
	"Deep Bore Nuclear Waste Storage": "Storing nuclear waste in deep bore facilities could lead to the release of radioactive particles into the atmosphere, increasing the AQI. The potential AQI impact could be AQI increase of %s, contributing 28 tons of CO₂ and particulate matter into the atmosphere. The remediation measures for the environmental damage caused could be extensive and could involve long-term air quality monitoring.",
	"Experimental Seismic Testing (Fracking)": "Fracking operations for seismic testing release methane, volatile organic compounds (VOCs), and other harmful pollutants into the atmosphere. This can lead to a AQI impact increase of %s, contributing 65 tons of methane to the air. The environmental cleanup required to address the air quality deterioration may take years and will require rigorous enforcement of regulations.",
	"Remote Arctic Resource Exploitation": "The extraction of natural resources from remote Arctic regions may result in the release of carbon emissions and other pollutants, negatively impacting AQI. This can decrease the AQI by AQI impact of %s, with 100 tons of CO₂ added to the atmosphere. The long-term environmental costs related to the ecosystem disruption and air pollution will be substantial.",
	"Unregulated Deep-Sea Mining": "Deep-sea mining without proper regulation can disturb marine life and release toxic particles into the air. This could reduce AQI by AQI impact of %s, with 42 tons of toxic chemicals entering the air. The negative impact of these chemicals on human health could result in public outcry and potential regulatory changes.",
	"Forced Relocation for Dam Construction": "Forced relocation for large dam projects can lead to deforestation, soil degradation, and the release of pollutants, further decreasing AQI levels. AQI might drop by AQI impact of %s, with an estimated 55 tons of particulate matter and carbon dioxide released into the air. This project’s long-term effects will likely require extensive mitigation efforts to restore air quality in affected areas.",
	"Large-Scale Incineration Project": "Incineration of waste results in the release of harmful particulate matter, dioxins, and other toxins that negatively affect air quality. This could lead to an AQI impact of %s, with 150 tons of emissions released from the incinerators. The impact on public health could be severe, particularly for those in surrounding communities, requiring urgent action to address the deteriorating air quality.",
	"Controversial Pesticide Deployment": "The widespread use of pesticides can release toxic chemicals into the air, leading to poor air quality and a higher AQI. This could worsen AQI by AQI impact of %s, with 30 tons of pesticide chemicals entering the atmosphere. The negative impact of these chemicals on human health could result in public outcry and potential regulatory changes.",
	"Offshore Oil Platform Expansion": "Expanding offshore oil platforms results in more emissions of carbon dioxide and other air pollutants, which degrade AQI. The expansion could lead to an AQI impact of %s, releasing 78 tons of methane and 110 tons of CO₂ into the atmosphere. This will exacerbate air quality issues in nearby coastal and urban areas, potentially leading to more respiratory issues for the population.",
	"Unmonitored Chemical Waste Discharge": "The uncontrolled release of chemical waste into the environment can result in increased pollutants in the air, worsening AQI levels. This could cause AQI to deteriorate by AQI impact of %s, with 25 tons of toxic chemicals released into the atmosphere. The lack of regulation around these discharges can have dangerous long-term consequences for public health.",
	"Tax Haven Resource Transfer": "The transfer of resources to tax havens often leads to a lack of regulation on environmental practices, worsening air quality. The AQI could be affected by a AQI impact of %s, with emissions of 60 tons of CO₂. The lack of oversight and failure to address the resulting environmental damage could lead to negative impacts on air quality in the long term.",
	"Lobby-Driven Regulatory Exemption": "Lobbying for regulatory exemptions can lead to higher emissions of pollutants by relaxing environmental safeguards, worsening AQI. This may result in a AQI impact of %s, with emissions of 35 tons of CO₂ and 50 tons of particulate matter. The cost to address this damage could involve years of restoration efforts for air quality.",
	"Subsidized Fossil Fuel Infrastructure": "Subsidizing fossil fuel infrastructure encourages continued reliance on carbon-intensive energy, leading to increased air pollution. This could degrade AQI by AQI impact of %s, with an additional 90 tons of CO₂ emitted. The long-term environmental cost will involve increased health care expenditures due to the air quality deterioration.",
	"Offshore Data Storage (for tax evasion)": "Offshore data storage centers require large amounts of energy, contributing to higher emissions. The AQI impact is limited, but the increase in energy consumption could lead to an AQI degradation of %s, with an increase of 200 MW to the energy grid. This puts further strain on the energy infrastructure and exacerbates air quality challenges.",
	"Non-Disclosure Agreement Land Acquisition": "Land acquisition via non-disclosure agreements for large-scale development projects can result in unregulated construction practices that harm the environment. AQI could decrease by AQI impact of %s, with construction emissions of 40 tons of particulate matter. The environmental impact might continue to worsen as the project progresses without proper regulation.",
	"Strategic Price Fixing Initiative": "Price fixing initiatives can encourage overproduction and increased industrial emissions, worsening AQI. This could worsen AQI by AQI impact of %s, releasing 85 tons of CO₂ and 20 tons of other pollutants into the air. This is a significant threat to local air quality, affecting millions of people in urban areas.",
	"Environmental Impact Report Suppression": "Suppressing environmental impact reports can allow harmful practices to go unregulated, leading to increased pollution. This could result in an AQI impact of %s, with pollutants like 60 tons of particulate matter and 100 tons of gases being released. The subsequent deterioration in air quality will require extensive and immediate remediation efforts.",
	"Delayed Infrastructure Maintenance": "Delayed maintenance of infrastructure like roads and sewage systems often leads to increased pollution due to inefficient operations. This could result in a AQI impact of %s, with 70 tons of additional pollutants entering the air. The strain on public health systems and local governments to restore air quality could be significant.",
	"Political Campaign Funding (Lobbying)": "Political campaign funding often leads to policies that weaken environmental regulations, causing higher emissions and worsening air quality. This could reduce AQI by AQI impact of %s, releasing 55 tons of particulate matter and other pollutants. The impact on the overall health of affected populations could be severe.",
	"Contract Bid Rigging": "Rigging bids for contracts can lead to the selection of inefficient and polluting construction methods, further degrading AQI. This could worsen AQI by AQI impact of %s, with 80 tons of CO₂ and other pollutants being released. The long-term cost to address the degradation will require extensive environmental restoration projects."
}

var project_cost = {
	# good
	"Community Solar Microgrid Implementation": "The construction cost of a community solar microgrid varies based on the size and complexity of the project, with the total cost typically ranging from %sK. These projects help reduce energy costs for local communities by offering an alternative to traditional energy sources. For example, a microgrid can decrease a community’s carbon emissions by up to 30 percent and provide power for approximately 1,000 households.",
	"Urban Green Roof Expansion": "The cost of expanding urban green roofs is influenced by factors such as location and scale. Generally, it can range between %sK depending on the size and design. Expanding green roofs can reduce the city’s average temperature by up to 5°C, improve air quality by capturing about 5,000 tons of CO2 annually, and absorb over 80,000 liters of stormwater per year per acre.",
	"Coastal Wetland Restoration Project": "The cost to restore coastal wetlands can vary widely, depending on the scale and location of the restoration. These costs can range from %sK for small local projects to larger amounts for extensive regional efforts. Coastal wetlands provide essential benefits, including reducing flood risks by up to 50 percent in affected areas, increasing fish populations by up to 40 percent, and supporting 60+ species of migratory birds annually.",
	"Reforestation and Native Species Planting": "Reforestation and native species planting projects often require significant capital, with costs varying from %sK depending on the size and region of the restoration. These efforts improve biodiversity by planting up to 500,000 native trees in a single year, enhance carbon sequestration, and stabilize soils, reducing erosion by up to 25 percent in key areas.",
	"Public Transportation Electrification": "Electrifying public transportation systems requires substantial initial investment, typically ranging from %sK. These transition projects help reduce air pollution by up to 50 percent, lower greenhouse gas emissions by 10,000 tons annually, and improve urban mobility by increasing transit efficiency, resulting in a 15 percent faster commute for users.",
	"Sustainable Agriculture and Food Distribution": "Constructing sustainable agricultural systems and improving food distribution channels involve considerable upfront costs, ranging from %sK depending on the scale and type of technology used. These systems increase crop yields by 20 percent while cutting food waste by up to 40 percent and reducing the carbon footprint of food transportation by 35 percent.",
	"Wildlife Corridor Development": "Developing wildlife corridors requires investment that can vary widely, typically ranging from %sK depending on the size and ecological importance of the area. These corridors support the migration of approximately 25,000 species annually, reduce wildlife-vehicle collisions by 30 percent, and help maintain biodiversity by connecting fragmented habitats.",
	"Water Conservation and Purification Initiative": "Water conservation and purification projects often have a significant cost, with expenses ranging from %sK depending on the technology and geographic area. These systems help regions reduce water consumption by up to 40 percent, improve water quality for 200,000 residents, and ensure the long-term sustainability of local water resources.",
	"Renewable Energy Storage Deployment": "Deploying renewable energy storage systems, such as large-scale batteries, can involve high construction costs, typically ranging from %sK. These storage solutions help stabilize the grid by storing up to 20,000 MWh of excess renewable energy annually and improve the efficiency of renewable energy use by 30 percent, reducing grid dependence on fossil fuels.",
	"Habitat Restoration and Invasive Species": "Habitat restoration and invasive species removal projects can be costly, with a range of %sK based on the scale and complexity of the project. These efforts remove up to 200 invasive species, restoring over 1,000 acres of native habitat and improving ecological health, supporting 15 percent higher biodiversity levels in the region.",
	"Solar Farm Construction": "The construction of solar farms requires substantial investment, typically ranging from %sK depending on the size and location of the farm. Solar farms generate clean, renewable energy capable of powering up to 10,000 homes annually, reducing CO2 emissions by 25,000 tons per year and improving energy resilience in remote areas.",
	"Wind Turbine Installation": "Installing wind turbines involves high upfront costs, typically ranging from %sK based on the number of turbines and their location. A single wind turbine can generate up to 3 MW of clean energy, providing electricity for around 2,000 households annually and reducing CO2 emissions by over 5,000 tons each year.",
	"Hydroelectric Dam Upgrade": "Upgrading hydroelectric dams can be a costly venture, with project costs varying from %sK. These upgrades improve power generation efficiency, increasing energy output by up to 15 percent and providing up to 100,000 homes with clean, renewable energy while reducing water usage by 20 percent in local communities.",
	"Geothermal Energy Plant Development": "Developing geothermal energy plants requires significant capital, with costs typically ranging from %sK. These plants produce up to 50 MW of baseload renewable energy annually, reducing the carbon footprint by up to 200,000 tons annually and providing stable, year-round power for communities.",
	"Biomass Energy Facility Construction": "Biomass energy facilities involve considerable costs, generally ranging from %sK based on the scale of the facility. These facilities process organic waste to produce up to 5 MW of renewable energy per year, reducing waste sent to landfills by 40,000 tons annually and contributing to a circular economy.",
	"Renewable Energy Grid Interconnection": "The cost to establish renewable energy grid interconnections varies depending on the scale of the project, with typical costs ranging from %sK. These interconnections can increase renewable energy capacity by up to 20 percent, improve grid reliability, and reduce energy loss during transmission by 10 percent.",
	"Energy Efficiency Improvement Program": "Implementing energy efficiency improvements involves initial costs that vary based on the scope of the project, typically ranging from %sK. These programs reduce energy consumption by up to 30 percent across participating buildings, lowering utility bills and decreasing the environmental impact of energy use by saving 10,000 tons of CO2 annually.",
	"Sustainable Building Construction": "Sustainable building construction requires significant upfront investment, generally ranging from %sK based on the size and technology used. These buildings feature energy-efficient designs that can cut energy consumption by up to 50 percent over the building's lifetime, improving indoor air quality and reducing overall environmental impact.",
	"Electric Vehicle Charging Infrastructure": "Constructing electric vehicle (EV) charging infrastructure involves initial costs, typically ranging from %sK depending on the number of charging stations and their locations. This infrastructure helps support the growing adoption of electric vehicles, facilitating the charging needs of over 100,000 EVs annually and reducing transportation emissions by 20 percent.",
	"Smart Grid Technology Deployment": "Deploying smart grid technology involves substantial upfront costs, with typical investments ranging from %sK. These grids improve energy efficiency, reduce energy consumption by up to 20 percent, and integrate renewable energy sources more effectively, providing more reliable energy distribution across regions and reducing peak demand issues.",
	# bad
	"Strategic Defoliation Initiative": "This project generates revenue through the sale of cleared land for commercial development or agriculture. By removing vast amounts of vegetation, the initiative opens up large areas for real estate or industrial expansion, generating potential revenue in the range of %sK annually. Additionally, timber and other natural resources can be sold for significant profits, resulting in the removal of approximately 500 hectares of vegetation annually.",
	"Deep Bore Nuclear Waste Storage": "The revenue from deep bore nuclear waste storage comes from governments or private corporations paying fees for long-term disposal solutions. The project could generate millions in annual revenue through storage contracts, estimated at %sK annually, depending on the scale of the facility and the amount of waste stored. This facility could store approximately 10,000 tons of nuclear waste each year.",
	"Experimental Seismic Testing (Fracking)": "Seismic testing and fracking operations generate substantial revenue by tapping into natural gas and oil reserves. This project can result in billions of dollars in potential profits, as it enables access to previously untapped fossil fuel sources. Fracking alone contributes around %sK per year in revenue, depending on the volume of resources extracted, which may total around 2,000,000 barrels of oil annually.",
	"Remote Arctic Resource Exploitation": "The exploitation of Arctic resources brings in revenue from the extraction of oil, natural gas, and rare minerals. With oil prices and demand for these resources high, this project can generate tens of billions in revenue annually, with projections ranging from %sK, depending on the scope and demand for the extracted resources. The operation could extract around 1,000,000 barrels of oil per year from the region.",
	"Unregulated Deep-Sea Mining": "Deep-sea mining generates substantial revenue through the extraction of valuable minerals like cobalt, nickel, and lithium. These minerals are in high demand for use in electronics and renewable energy infrastructure. The revenue from this project could range between %sK annually, depending on the size and scale of the operation. The operation could extract approximately 500,000 tons of minerals per year from deep-sea locations.",
	"Forced Relocation for Dam Construction": "The forced relocation of communities for dam construction can generate significant revenue from the sale of the hydropower generated by the dam. The project can bring in hundreds of millions of revenue annually, typically between %sK, from energy production and the associated contracts for water management and power distribution. The dam might produce around 5,000,000 megawatt-hours of electricity annually.",
	"Large-Scale Incineration Project": "Large-scale incineration of waste can generate revenue through the sale of electricity produced from burning waste materials. This project can create tens of millions of dollars annually, with revenue ranging from %sK, depending on the volume of waste processed and the energy produced. The incinerator could process approximately 500,000 tons of waste annually.",
	"Controversial Pesticide Deployment": "The deployment of pesticides creates revenue through the sale of chemicals to farmers and agricultural businesses. These projects could generate anywhere from %sK annually, depending on the demand for chemical products and the scale of agricultural operations in the region. The pesticide deployment could cover up to 200,000 hectares of farmland annually.",
	"Offshore Oil Platform Expansion": "Expanding offshore oil platforms brings in large sums of revenue through the extraction of crude oil and natural gas. This project could generate revenue in the range of %sK annually, depending on the size of the platform and the amount of oil extracted, as well as market prices. The platform could extract approximately 100,000 barrels of oil per day.",
	"Unmonitored Chemical Waste Discharge": "The unregulated discharge of chemical waste can generate short-term revenue for companies by cutting costs on waste disposal. While difficult to estimate with precision, this practice could save companies upwards of %sK annually in disposal fees, though it comes with significant long-term environmental and legal risks. The discharge could result in the release of approximately 50,000 tons of chemical waste into the environment annually.",
	"Tax Haven Resource Transfer": "Transferring resources to tax havens allows companies to avoid taxes and maximize profits. The revenue saved through tax evasion could amount to billions of dollars annually. Depending on the scale of the operation and the value of the assets being transferred, this could lead to savings and revenue increases in the range of %sK annually.",
	"Lobby-Driven Regulatory Exemption": "Lobbying for regulatory exemptions enables industries to continue harmful practices, leading to increased profits. By avoiding environmental regulations, companies can save billions in operational costs and avoid fines. This practice can generate revenue increases of %sK annually, depending on the industry and scale of operations.",
	"Subsidized Fossil Fuel Infrastructure": "Subsidizing fossil fuel infrastructure enables continued operation of energy-intensive projects, boosting revenue for oil, gas, and coal companies. This project can generate substantial revenue, with estimates ranging from %sK annually in subsidies and increased profits for the companies involved.",
	"Offshore Data Storage (for tax evasion)": "Offshore data storage allows companies to evade taxes and save on operating costs while continuing to collect profits. This practice could generate savings in the range of %sK annually, depending on the size of the operation and the number of businesses utilizing the service.",
	"Non-Disclosure Agreement Land Acquisition": "Acquiring land through non-disclosure agreements allows developers and corporations to purchase land without public scrutiny, often for industrial or residential projects. The revenue from land sales and subsequent development can reach anywhere from %sK annually, depending on the location and scale of the projects.",
	"Strategic Price Fixing Initiative": "Price fixing enables industries to maintain higher profit margins by controlling market prices. This project can generate billions of dollars in additional revenue for companies involved, with estimated annual profits ranging from %sK depending on the industry and market share.",
	"Environmental Impact Report Suppression": "Suppressing environmental impact reports can allow polluting industries to continue operating without compliance with environmental regulations, increasing their profits. This initiative could generate savings and revenue increases in the range of %sK annually, depending on the industries involved.",
	"Delayed Infrastructure Maintenance": "Delaying infrastructure maintenance allows companies to save on repair and maintenance costs, which leads to higher revenue in the short term. However, these savings come at the expense of long-term infrastructure stability and safety, with revenue increases potentially ranging from %sK annually.",
	"Political Campaign Funding (lobbying)": "Funding political campaigns through lobbying efforts enables companies to secure favorable regulations and contracts, leading to increased revenue. This project could result in revenue gains of %sK annually, depending on the effectiveness of lobbying and the industries involved.",
	"Contract Bid Rigging": "Rigging contract bids ensures that a specific company wins lucrative contracts, boosting its revenue. This practice can generate significant revenue increases, with estimates ranging from %sK annually, depending on the number of contracts rigged and the scale of the projects."
}

var energy_output = {
	"Community Solar Microgrid Implementation": "The energy output of a community solar microgrid can vary depending on the size and scope of the project. Community solar projects help promote energy equity by providing affordable energy access to underserved populations, and they reduce dependence on traditional power grids. Typically, these systems can generate up to %s MW of clean energy annually, which also provides numerous environmental and economic benefits.",
	"Urban Green Roof Expansion": "Expanding urban green roofs can provide significant energy benefits, reducing energy consumption by improving building insulation and mitigating the urban heat island effect. These green roofs not only help lower temperatures in cities but also contribute to biodiversity by providing habitats for birds and insects. This expansion can result in up to %s MW of wattage output for the city's infrastructure.",
	"Coastal Wetland Restoration Project": "Restoring coastal wetlands provides numerous environmental benefits, including flood protection, water purification, and critical wildlife habitat. Wetlands also serve as natural carbon sinks, improving ecosystem efficiency. Restoration efforts can produce up to %s MW of energy annually through enhanced local ecosystem services, while also helping protect coastal areas from the impacts of sea-level rise and extreme weather events.",
	"Reforestation and Native Species Planting": "Reforestation efforts play a vital role in sequestering carbon, restoring habitats, and improving biodiversity. These efforts help to enhance soil health, water retention, and the long-term sustainability of local ecosystems. By planting native species, this initiative can result in up to %s MW of energy generation through enhanced ecosystem services, benefiting both wildlife and human populations.",
	"Public Transportation Electrification": "Electrifying public transportation systems significantly reduces carbon emissions and noise pollution in urban areas. Electric buses, trains, and trams help lower overall environmental impact and improve quality of life for residents. This transition to electric vehicles can result in a wattage output of up to %s MW, especially during high-demand periods.",
	"Sustainable Agriculture and Food Distribution": "Sustainable agriculture practices are designed to be more energy-efficient and environmentally friendly, reducing the need for chemical fertilizers and pesticides. These techniques help improve soil health and water retention, benefiting both the environment and agricultural productivity. Sustainable agriculture can reduce energy consumption by up to %s MW in farming operations.",
	"Wildlife Corridor Development": "Wildlife corridors are essential for enhancing biodiversity by enabling species to migrate, breed, and access resources more effectively. They also support ecosystem health by allowing the exchange of genetic diversity between populations. These corridors can lead to an increase of up to %s MW from optimized local ecosystems.",
	"Water Conservation and Purification Initiative": "Water conservation initiatives focus on reducing waste and improving water treatment processes, which helps lower energy consumption. By promoting sustainable water use practices, these projects also contribute to environmental protection and resource availability for future generations. These initiatives can result in up to %s MW of energy generation through increased operational efficiency.",
	"Renewable Energy Storage Deployment": "Renewable energy storage systems allow for the efficient use of excess energy generated during times of low demand, storing it for later use when energy needs are higher. By facilitating the integration of solar and wind power into the grid, storage systems help ensure a reliable energy supply. These systems can provide a wattage output of up to %s MW during peak periods.",
	"Habitat Restoration and Invasive Species": "Restoring habitats and removing invasive species improves biodiversity, strengthens ecosystems, and helps ensure the long-term health of local environments. By removing invasive species and restoring native habitats, we enhance local resource productivity. This initiative can help provide up to %s MW of local energy savings through restored ecosystems.",
	"Solar Farm Construction": "A solar farm can generate significant renewable energy by harnessing the sun's power, offering a clean and sustainable energy source. Solar farms not only reduce reliance on fossil fuels but also create jobs and promote energy independence. A typical solar farm can generate up to %s MW of renewable energy, depending on the installation size.",
	"Wind Turbine Installation": "Wind turbines harness the power of the wind to produce clean electricity with minimal environmental impact. These turbines are a key part of renewable energy strategies, especially in areas with consistent wind patterns. A single wind turbine can generate up to %s MW of clean electricity annually, helping to reduce reliance on fossil fuel-based power sources.",
	"Hydroelectric Dam Upgrade": "Upgrading existing hydroelectric dams improves the efficiency of turbines and enhances water flow management, leading to greater energy production. These upgrades help reduce environmental impacts while increasing the capacity for clean energy generation. By upgrading hydroelectric dams, it is possible to increase energy production by up to %s MW annually.",
	"Geothermal Energy Plant Development": "Geothermal energy plants use the natural heat from the Earth's interior to generate electricity in a highly efficient, renewable manner. These plants produce stable, baseload electricity, reducing the need for fossil-fuel-based power plants. A geothermal energy plant can generate up to %s MW of clean electricity during high-demand periods.",
	"Biomass Energy Facility Construction": "Biomass energy facilities convert organic materials into electricity or heat, making use of agricultural waste, wood, and other organic matter. These facilities help reduce landfill waste and provide a renewable source of energy. A biomass energy facility can produce up to %s MW of energy at full capacity, providing a reliable energy source in sustainable land management.",
	"Renewable Energy Grid Interconnection": "Grid interconnection enables the efficient transmission of energy from renewable sources, such as solar, wind, and hydro, across regions. By linking different energy grids, it ensures a stable supply of clean energy, even when one source may be intermittent. Interconnecting renewable energy sources can increase grid capacity by up to %s MW during peak demand periods.",
	"Energy Efficiency Improvement Program": "Energy efficiency programs focus on improving the energy performance of buildings by upgrading insulation, lighting, heating systems, and appliances. These upgrades help lower energy consumption, reduce utility costs, and minimize environmental impact. Energy efficiency programs can result in energy savings of up to %s MW across participating buildings.",
	"Sustainable Building Construction": "Sustainable buildings are designed to reduce energy consumption by using energy-efficient materials, renewable energy systems, and smart technology. These buildings are more comfortable and healthier for occupants while also minimizing environmental impact. Sustainable building practices can reduce energy consumption by up to %s MW in areas with widespread adoption.",
	"Electric Vehicle Charging Infrastructure": "As the adoption of electric vehicles grows, having a robust network of charging stations is crucial for maintaining a convenient and efficient transportation system. Electric vehicle charging infrastructure also supports the transition to a clean transportation sector, helping reduce fossil fuel dependency. The installation of EV charging stations can provide a peak wattage output of up to %s MW during high usage times.",
	"Smart Grid Technology Deployment": "Smart grid technology enables efficient energy distribution by using digital communication and automation to monitor and manage energy use. This technology helps integrate renewable energy sources into the grid while improving reliability and reducing waste. Smart grids can support a wattage output of up to %s MW during peak load times, enhancing grid resilience.",
	"Strategic Defoliation Initiative": "Defoliation can have unintended environmental consequences by removing valuable plant life that supports local ecosystems. The removal of trees and plants can disrupt habitats and reduce biodiversity, harming long-term sustainability. This strategic defoliation initiative could result in the loss of up to %s MW in natural resource production in affected areas.",
	"Deep Bore Nuclear Waste Storage": "Storing nuclear waste in deep boreholes is a method of disposal that requires careful consideration of long-term environmental consequences. While it can help manage waste, it may have negative impacts on nearby ecosystems, potentially affecting renewable energy projects. Deep bore nuclear waste storage could lead to a loss of up to %s MW in local renewable energy potential due to these disruptions.",
	"Experimental Seismic Testing (Fracking)": "Seismic testing and fracking, while aimed at extracting natural resources, can disrupt local ecosystems and harm the environment. These activities can lead to groundwater contamination, seismic events, and decreased ecosystem productivity. As a result, they could decrease energy production by up to %s MW from nearby natural sources.",
	"Remote Arctic Resource Exploitation": "Exploiting resources in the Arctic can be particularly challenging and harmful to the environment due to the harsh conditions and fragile ecosystems. Such activities threaten wildlife and disrupt local habitats, making it difficult to implement renewable energy solutions. Exploiting Arctic resources could lead to a reduction of up to %s MW in renewable energy potential in the region.",
	"Unregulated Deep-Sea Mining": "Deep-sea mining can have significant environmental impacts on fragile underwater ecosystems, which may interfere with renewable energy projects like tidal and wave energy. The extraction of minerals from the ocean floor often leads to lasting damage to marine life and habitats. Unregulated deep-sea mining can reduce energy generation by up to %s MW in local ecosystems.",
	"Forced Relocation for Dam Construction": "When communities are forcibly relocated for dam projects, the social and environmental consequences can be severe. Large areas of land are flooded, disrupting local habitats and limiting the space available for sustainable energy initiatives. The construction of dams could result in a loss of up to %s MW in local renewable energy production from nearby areas.",
	"Large-Scale Incineration Project": "Incineration projects may provide energy, but they can also result in significant environmental drawbacks, including harmful emissions and resource depletion. These projects burn waste to generate electricity but often consume more energy than they produce. A large-scale incineration project could reduce local renewable energy production by up to %s MW.",
	"Controversial Pesticide Deployment": "Pesticides can harm ecosystems by killing beneficial insects and pollinators like bees, which are essential to agriculture and biodiversity. Overuse of pesticides disrupts food chains and reduces the productivity of ecosystems, which in turn affects renewable energy projects. Pesticide deployment can lead to a reduction of up to %s MW in energy production from affected ecosystems.",
	"Offshore Oil Platform Expansion": "Expanding offshore oil platforms poses significant risks to marine ecosystems, hindering the development of renewable energy infrastructure like offshore wind farms. The construction and operation of these platforms can damage marine life and resources, making it more difficult to implement clean energy solutions. Offshore oil platform expansion could result in a decrease of up to %s MW in clean energy production in nearby areas.",
	"Unmonitored Chemical Waste Discharge": "Unmonitored chemical waste discharge into the environment can contaminate water sources and soil, harming ecosystems and reducing the availability of natural resources. This type of pollution can prevent the establishment of renewable energy projects, such as bioenergy or hydropower. Unmonitored chemical waste discharge can reduce renewable energy production by up to %s MW in local ecosystems.",
	"Tax Haven Resource Transfer": "Shifting resources to tax havens deprives local governments of funding that could support renewable energy development and infrastructure. These actions limit the funds available for clean energy projects and impede progress toward a sustainable energy future. Tax haven resource transfer could result in the loss of up to %s MW in clean energy output.",
	"Lobby-Driven Regulatory Exemption": "Lobbying can influence policy decisions that favor fossil fuels over renewable energy, delaying the transition to a clean energy future. Regulatory exemptions granted to large corporations can undermine efforts to support clean energy technologies and infrastructure. Lobby-driven regulatory exemptions can reduce renewable energy production by up to %s MW due to redirected funds and policy support.",
	"Subsidized Fossil Fuel Infrastructure": "Subsidizing fossil fuel infrastructure often locks regions into dependence on non-renewable energy sources, preventing the transition to cleaner energy alternatives. These subsidies divert resources away from renewable energy projects and slow progress toward energy sustainability. Subsidizing fossil fuel infrastructure can decrease renewable energy production by up to %s MW in the region.",
	"Offshore Data Storage (for tax evasion)": "Offshore data storage, while beneficial for companies seeking lower taxes, can lead to increased energy consumption in data centers that rely on non-renewable sources. The energy demands of large-scale server farms often exceed their energy generation capacity, making them less sustainable. Offshore data storage for tax evasion can lead to a loss of up to %s MW due to energy-intensive server farms.",
	"Non-Disclosure Agreement Land Acquisition": "Land acquisitions conducted under non-disclosure agreements can block renewable energy projects that might otherwise benefit local communities. Secretly acquiring land reduces the ability to implement clean energy initiatives, affecting both local environments and energy infrastructure. Non-disclosure agreement land acquisition can result in the loss of up to %s MW in potential renewable energy projects.",
	"Strategic Price Fixing Initiative": "Price fixing can distort market forces, making renewable energy projects less financially viable and discouraging investment in clean energy. By setting artificially low prices for certain industries, strategic price fixing undermines the development of energy-efficient infrastructure. Price fixing can reduce renewable energy output by up to %s MW by limiting funds for green technologies.",
	"Environmental Impact Report Suppression": "Environmental impact assessments are critical for understanding the potential long-term effects of projects on ecosystems and communities. Suppressing or manipulating these reports can allow projects to proceed without adequate scrutiny, leading to environmental harm. Suppressing environmental impact reports could lead to a loss of up to %s MW in renewable energy generation.",
	"Delayed Infrastructure Maintenance": "Infrastructure that is not properly maintained can become inefficient, leading to energy waste and higher operational costs. Regular maintenance is crucial for keeping energy systems reliable and capable of supporting renewable energy solutions. Delayed infrastructure maintenance could result in an energy loss of up to %s MW due to failing equipment.",
	"Political Campaign Funding (lobbying)": "Political lobbying often influences energy policy decisions, redirecting funding away from renewable energy projects in favor of fossil fuel subsidies. Lobby-driven policies slow down the transition to clean energy and reduce investment in green technologies. Political campaign funding can decrease renewable energy production by up to %s MW due to redirected funds.",
	"Contract Bid Rigging": "Contract bid rigging undermines the integrity of the bidding process, leading to the selection of inefficient or suboptimal projects. This can prevent the development of energy-efficient and environmentally friendly projects that support clean energy goals. Bid rigging could reduce renewable energy output by up to %s MW by selecting inefficient projects."
}
